name = "burnout-anonymizer"
main = "index.js"
compatibility_date = "2024-01-01"

# Configuração de rotas
routes = [
  { pattern = "burnout-proxy.your-domain.workers.dev", zone_name = "your-domain.com" }
]

# Variáveis de ambiente (configure no dashboard do Cloudflare)
[vars]
BACKEND_URL = "https://your-backend-api.com"
